export const GET_USER_DETAILS_REQUEST = "/GET_USER_DETAILS_REQUEST ";
export const GET_USER_DETAILS_SUCCESS = "/GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "/GET_USER_DETAILS_FAIL";
