export const GET_SCREENING_DATE_RANGE_REQUEST = "GET_SCREENING_DATE_RANGE_REQUEST";
export const GET_SCREENING_DATE_RANGE_SUCCESS = "GET_SCREENING_DATE_RANGE_SUCCESS";
export const GET_SCREENING_DATE_RANGE_FAIL = "GET_SCREENING_DATE_RANGE_FAIL";
