export const GET_SCREENING_BY_FILM_ID_REQUEST = "GET_SCREENING_BY_FILM_ID_REQUEST";
export const GET_SCREENING_BY_FILM_ID_SUCCESS = "GET_SCREENING_BY_FILM_ID_SUCCESS";
export const GET_SCREENING_BY_FILM_ID_FAIL = "GET_SCREENING_BY_FILM_ID_FAIL";
