export const GET_SEATS_BY_SCREENING_ID_REQUEST = "GET_SEATS_BY_SCREENING_ID_REQUEST";
export const GET_SEATS_BY_SCREENING_ID_SUCCESS = "GET_SEATS_BY_SCREENING_ID_SUCCESS";
export const GET_SEATS_BY_SCREENING_ID_FAIL = "GET_SEATS_BY_SCREENING_ID_FAIL";
